outdir: "/mnt/data/tj/2fold_voco_data/outputs/finetune_ccccii_fold0"
data_dir: "/mnt/data/tj/2fold_voco_data/data_finetune/CC-CCII_public/data"
csv_list: "/mnt/data/tj/2fold_voco_data/data_finetune/CC-CCII_public/csv"
fold: 0  # cross-validation fold
batch_size: 4
lr: 0.0003
weight_decay: 0.00001
epochs: 100
seed: 42
pretrain_checkpoint: "/mnt/data/tj/2fold_voco_data/outputs/pretrain_16k_1/best.pt"
in_channels: 1
num_classes: 3  # out channels
feature_size: 48
spatial_dims: 3
dropout_path_rate: 0.0
start_epoch: 0  # in case you resume from a checkpoint
resume_checkpoint: null  # use null instead of None if no checkpoint is used
amp: false
val_every: 5
use_checkpoint: true
save_every: 10

