dataset: "brats_18"
outdir: /mnt/data/tj/data/2fold_voco_data/outputs/finetune_brats18_mask_char_all_train_p4_m5_eval"
data_dir: "/mnt/data/tj/data/2fold_voco_data/finetune_data/Task01_BrainTumour"
cache_dir: "/mnt/data/tj/data/2fold_voco_data/data_cache/Task01_BrainTumour_18"
json_list: "brats.json"
batch_size: 1
workers: 2
lr: 0.0003
weight_decay: 0.00001
epochs: 500
seed: 42
pretrain_checkpoint: "/mnt/data/tj/data/2fold_voco_data/outputs/pretrain_16k_mask_char_all_train/best.pt"
in_channels: 4
num_classes: 4 # out channels
feature_size: 48
spatial_dims: 3
dropout_path_rate: 0.0
start_epoch: 0  # in case you resume from a checkpoint
resume_checkpoint: null  # use null instead of None if no checkpoint is used
amp: true
val_every: 1000
use_checkpoint: true
save_every: 50
space_x: 1.0
space_y: 1.0
space_z: 1.0
a_min: -175.0
a_max: 250.0
b_min: 0.0
b_max: 1.0
roi_x: 128
roi_y: 128
roi_z: 128
use_normal_dataset: true
RandFlipd_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
RandRotate90d_prob: 0.2
sw_batch_size: 2
infer_overlap: 0.75
test_mode: false
fold: null
datafold_read: true
class_names: ["edema", "non-enhancing tumor", "enhancing tumor"]
checkpoint: "/mnt/data/tj/data/2fold_voco_data/outputs/finetune_brats18_mask_char_all_train_p4_m5/150.pt"
ignore_empty_gt: false

#false: include empty patients in the avg, 
#true: emove empty patients from the average
