dataset: "btcv"
data_dir: "/mnt/data/tj/data/2fold_voco_data/finetune_data/BTCV"
cache_dir: "/mnt/data/backup/tj/2fold_voco_data/data_load_cache/BTCV"
json_list: "dataset_0.json"
batch_size: 1 #1
workers: 8 
lr: 0.0003
weight_decay: 0.00001
epochs: 1000 #1000
seed: 42
in_channels: 1
num_classes: 14 # out channels
feature_size: 48
spatial_dims: 3
dropout_path_rate: 0.0
start_epoch: 0  # in case you resume from a checkpoint
checkpoint: "/mnt/data/tj/data/2fold_voco_data/outputs/finetune_btcv_mask_char_all_train_p4_m7/best.pt"
  #resume_checkpoint: "/mnt/data/backup/tj/2fold_voco_data/outputs/temp_lits/best.pt"  # use null instead of None if no checkpoint is used
amp: false
class_names: ["spleen","r.kid", "l.kid", "gall", "eso", "liver", "stomach", "aorta", "ivc", "veins", "pancreas","rag","lag"]
val_every: 5
use_checkpoint: true
save_every: 50
space_x: 1.5
space_y: 1.5
space_z: 1.5
a_min: -175.0
a_max: 250.0
b_min: 0.0
b_max: 1.0
roi_x: 96
roi_y: 96
roi_z: 96 
use_normal_dataset: true
RandFlipd_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
RandRotate90d_prob: 0.2
sw_batch_size: 4
infer_overlap: 0.75
test_mode: false
datafold_read: False
